name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Java SDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Maven compile
      id: maven-compile
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Maven compile
        setup-command: ''
        command: mvn compile
        timeout: 10
        max-score: 1
    - name: Maven Test
      id: maven-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Maven Test
        setup-command: ''
        command: mvn test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAVEN-COMPILE_RESULTS: "${{steps.maven-compile.outputs.result}}"
        MAVEN-TEST_RESULTS: "${{steps.maven-test.outputs.result}}"
      with:
        runners: maven-compile,maven-test
